---

- hosts: all
  become: yes
  tasks:
  -  name: Install motion on Ubuntu
     apt:
        name=motion
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        motion systemd
  handlers:
  - name: motion systemd
    systemd:
     name: motion.service
     enabled: yes
     state: started
